version: '3.4'

services:
  lmarena2api:
    image: deanxv/lmarena2api:latest
    container_name: lmarena2api
    restart: always
    ports:
      - "10088:10088"
    volumes:
      - ./data:/app/lmarena2api/data
    environment:
      - LA_COOKIE=******  # cookie (多个请以,分隔)
      - API_SECRET=123456  # [可选]接口密钥-修改此行为请求头校验的值(多个请以,分隔)
      - TZ=Asia/Shanghai